In [1]:
import pandas as pd
import sys
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

def load_data():
    return pd.read_csv('/Users/Kaemyuijang/SCMA248/Data/ClaimsExperienceData.csv')
claims = load_data()
claims.head()

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
claims['NumClaims'] = claims['Freq']

In [34]:
#claims.pivot_table(index = 'Freq', columns = 'Year', values = ['PolicyNum','NumClaims','PolicyNum'], aggfunc = {'PolicyNum':'count','NumClaims':'sum'}).rename(columns={'PolicyNum':'NumPolicies'})

claims.pivot_table(index = 'Freq', columns = 'Year', values = ['PolicyNum','NumClaims'], aggfunc = {'PolicyNum':['count',lambda x: x.count()],'NumClaims':'sum'})

     NumClaims                              PolicyNum                       \
           sum                             <lambda_0>
Year      2006   2007   2008   2009   2010       2006   2007   2008   2009
Freq
0          0.0    0.0    0.0    0.0    0.0      845.0  781.0  816.0  811.0
1        153.0  146.0  155.0  155.0  209.0      153.0  146.0  155.0  155.0
2        134.0  184.0  112.0  138.0  172.0       67.0   92.0   56.0   69.0
3        120.0  141.0  123.0   78.0  120.0       40.0   47.0   41.0   26.0
4         52.0  108.0   96.0   68.0   72.0       13.0   27.0   24.0   17.0
5         45.0   75.0   30.0   55.0   60.0        9.0   15.0    6.0   11.0
6         36.0   36.0   30.0    6.0   54.0        6.0    6.0    5.0    1.0
7          7.0   56.0   35.0   28.0   28.0        1.0    8.0    5.0    4.0
8         48.0   32.0   16.0   16.0   48.0        6.0    4.0    2.0    2.0
9         27.0    9.0   18.0   18.0    9.0        3.0    1.0    2.0    2.0
10        30.0    NaN   30.0   20.0   30.0        3.0    NaN    3.0    2.0
11        22.0    NaN   11.0   11.0   22.0        2.0    NaN    1.0    1.0
12         NaN   12.0   12.0   12.0    NaN        NaN    1.0    1.0    1.0
13         NaN    NaN   13.0   13.0   13.0        NaN    NaN    1.0    1.0
14        14.0   14.0   14.0    NaN   28.0        1.0    1.0    1.0    NaN
15         NaN   15.0    NaN   30.0   15.0        NaN    1.0    NaN    2.0
16         NaN   32.0    NaN   16.0   32.0        NaN    2.0    NaN    1.0
17         NaN   17.0    NaN    NaN   17.0        NaN    1.0    NaN    NaN
18         NaN   18.0   36.0   18.0   18.0        NaN    1.0    2.0    1.0
19         NaN    NaN    NaN   19.0   19.0        NaN    NaN    NaN    1.0
20        20.0    NaN   20.0    NaN    NaN        1.0    NaN    1.0    NaN
21         NaN    NaN    NaN   21.0    NaN        NaN    NaN    NaN    1.0
24        24.0    NaN    NaN    NaN    NaN        1.0    NaN    NaN    NaN
26         NaN   26.0    NaN    NaN    NaN        NaN    1.0    NaN    NaN
30         NaN    NaN    NaN    NaN   30.0        NaN    NaN    NaN    NaN
38         NaN   38.0    NaN    NaN    NaN        NaN    1.0    NaN    NaN
39         NaN    NaN    NaN    NaN   39.0        NaN    NaN    NaN    NaN
55         NaN    NaN   55.0    NaN    NaN        NaN    NaN    1.0    NaN
58        58.0    NaN    NaN    NaN    NaN        1.0    NaN    NaN    NaN
67         NaN    NaN   67.0    NaN    NaN        NaN    NaN    1.0    NaN
100      100.0    NaN    NaN    NaN    NaN        1.0    NaN    NaN    NaN
103        NaN    NaN    NaN    NaN  103.0        NaN    NaN    NaN    NaN
143        NaN    NaN    NaN  143.0    NaN        NaN    NaN    NaN    1.0
157        NaN  157.0    NaN    NaN    NaN        NaN    1.0    NaN    NaN
208      208.0    NaN    NaN    NaN    NaN        1.0    NaN    NaN    NaN
212        NaN  212.0    NaN    NaN    NaN        NaN    1.0    NaN    NaN
223        NaN    NaN  223.0    NaN    NaN        NaN    NaN    1.0    NaN
228        NaN    NaN    NaN  228.0    NaN        NaN    NaN    NaN    1.0
239        NaN    NaN    NaN    NaN  239.0        NaN    NaN    NaN    NaN
263        NaN    NaN    NaN  263.0    NaN        NaN    NaN    NaN    1.0


             count
Year   2010   2006   2007   2008   2009   2010
Freq
0     707.0  845.0  781.0  816.0  811.0  707.0
1     209.0  153.0  146.0  155.0  155.0  209.0
2      86.0   67.0   92.0   56.0   69.0   86.0
3      40.0   40.0   47.0   41.0   26.0   40.0
4      18.0   13.0   27.0   24.0   17.0   18.0
5      12.0    9.0   15.0    6.0   11.0   12.0
6       9.0    6.0    6.0    5.0    1.0    9.0
7       4.0    1.0    8.0    5.0    4.0    4.0
8       6.0    6.0    4.0    2.0    2.0    6.0
9       1.0    3.0    1.0    2.0    2.0    1.0
10      3.0    3.0    NaN    3.0    2.0    3.0
11      2.0    2.0    NaN    1.0    1.0    2.0
12      NaN    NaN    1.0    1.0    1.0    NaN
13      1.0    NaN    NaN    1.0    1.0    1.0
14      2.0    1.0    1.0    1.0    NaN    2.0
15      1.0    NaN    1.0    NaN    2.0    1.0
16      2.0    NaN    2.0    NaN    1.0    2.0
17      1.0    NaN    1.0    NaN    NaN    1.0
18      1.0    NaN    1.0    2.0    1.0    1.0
19      1.0    NaN    NaN    NaN    1.0    1.0
20      NaN    1.0    NaN    1.0    NaN    NaN
21      NaN    NaN    NaN    NaN    1.0    NaN
24      NaN    1.0    NaN    NaN    NaN    NaN
26      NaN    NaN    1.0    NaN    NaN    NaN
30      1.0    NaN    NaN    NaN    NaN    1.0
38      NaN    NaN    1.0    NaN    NaN    NaN
39      1.0    NaN    NaN    NaN    NaN    1.0
55      NaN    NaN    NaN    1.0    NaN    NaN
58      NaN    1.0    NaN    NaN    NaN    NaN
67      NaN    NaN    NaN    1.0    NaN    NaN
100     NaN    1.0    NaN    NaN    NaN    NaN
103     1.0    NaN    NaN    NaN    NaN    1.0
143     NaN    NaN    NaN    NaN    1.0    NaN
157     NaN    NaN    1.0    NaN    NaN    NaN
208     NaN    1.0    NaN    NaN    NaN    NaN
212     NaN    NaN    1.0    NaN    NaN    NaN
223     NaN    NaN    NaN    1.0    NaN    NaN
228     NaN    NaN    NaN    NaN    1.0    NaN
239     1.0    NaN    NaN    NaN    NaN    1.0
263     NaN    NaN    NaN    NaN    1.0    NaN

In [96]:
output = claims.pivot_table(index = 'Freq', columns = 'Year', values = 'PolicyNum', aggfunc = {'PolicyNum':lambda x: x.count()},margins=False)

In [97]:
output.head()

Year   2006   2007   2008   2009   2010
Freq
0     845.0  781.0  816.0  811.0  707.0
1     153.0  146.0  155.0  155.0  209.0
2      67.0   92.0   56.0   69.0   86.0
3      40.0   47.0   41.0   26.0   40.0
4      13.0   27.0   24.0   17.0   18.0

In [98]:
output.columns

Int64Index([2006, 2007, 2008, 2009, 2010], dtype='int64', name='Year')

In [99]:
def calPercent(df,colName):
    name = 'Proportion_' + str(colName)
    df[name]=100*df[colName]/(df[colName].sum())
    return df

In [101]:
calPercent(output,2010).head()

Year   2006   2007   2008   2009   2010  Proportion_2010
Freq
0     845.0  781.0  816.0  811.0  707.0        63.693694
1     153.0  146.0  155.0  155.0  209.0        18.828829
2      67.0   92.0   56.0   69.0   86.0         7.747748
3      40.0   47.0   41.0   26.0   40.0         3.603604
4      13.0   27.0   24.0   17.0   18.0         1.621622